#!/usr/bin/env bash
set -Eeuo pipefail
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$ROOT_DIR/.env"

# Source shared Supabase utility functions
if [[ -f "$ROOT_DIR/lib/supabase-utils.sh" ]]; then
  source "$ROOT_DIR/lib/supabase-utils.sh"
fi
SUPABASE_DIR="$ROOT_DIR/supabase"
ARCHON_SRC_DIR_DEFAULT="${ARCHON_SRC_DIR_OVERRIDE:-$ROOT_DIR/archon-src}"
ARCHON_SRC_BRANCH_DEFAULT="${ARCHON_SRC_BRANCH_OVERRIDE:-aeyeops/custom-main}"
ARCHON_SRC_DIR="$ARCHON_SRC_DIR_DEFAULT"
ARCHON_SRC_BRANCH="$ARCHON_SRC_BRANCH_DEFAULT"

default_observability="compose"
default_agents=1
default_work_orders=1
default_single_port=1
skip_verify=0
run_migrations=1
fresh_install=0
no_port_check=0

# Supabase startup configuration
SUPABASE_START_ATTEMPTS=1  # Reduce retries for faster failure feedback
SUPABASE_DEBUG=1           # Enable debug output for troubleshooting
# SUPABASE_VERSION is defined in lib/supabase-utils.sh (sourced above)

if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  echo -e "${RED}Docker Compose not found.${NC}" >&2; exit 1
fi

ok(){ echo -e "${GREEN}✓${NC} $1"; }
warn(){ echo -e "${YELLOW}!${NC} $1"; }
err(){ echo -e "${RED}✗${NC} $1"; }
container_exists(){ docker ps -a --format '{{.Names}}' | grep -qx "$1"; }

HOST_OVERRIDE=""; observability="$default_observability"; enable_agents=$default_agents; enable_work_orders=$default_work_orders; enable_single_port=$default_single_port

while [[ $# -gt 0 ]]; do
  case "$1" in
    --host) HOST_OVERRIDE="${2:-}"; shift 2;;
    --observability) observability="${2:-}"; shift 2;;
    --agents) enable_agents=1; shift;;
    --no-agents) enable_agents=0; shift;;
    --work-orders) enable_work_orders=1; shift;;
    --no-work-orders) enable_work_orders=0; shift;;
    --single-port) enable_single_port=1; shift;;
    --no-single-port) enable_single_port=0; shift;;
    --no-verify) skip_verify=1; shift;;
    --no-migrations) run_migrations=0; shift;;
    --fresh) fresh_install=1; shift;;
    --no-port-check) no_port_check=1; shift;;
    -h|--help)
      cat <<EOF
Usage: $(basename "$0") [--host <ip>] [--observability compose|script|none] [--no-agents] [--no-work-orders] [--no-single-port] [--no-verify] [--no-migrations] [--no-port-check] [--fresh]
Options:
  --work-orders   Enable agent work orders service (default: enabled)
  --no-work-orders Disable agent work orders service
  --fresh         Perform fresh database install (wipe and reinstall schema)
EOF
      exit 0;;
    *) err "Unknown option: $1"; exit 1;;
  esac
done

if [[ ! -f "$ENV_FILE" ]]; then
  if [[ -f "$ROOT_DIR/.env.sample" ]]; then
    cp "$ROOT_DIR/.env.sample" "$ENV_FILE"
    ok ".env created from .env.sample"
  else
    echo "# Generated by archon-up.sh" > "$ENV_FILE"
    ok ".env initialized (no .env.sample found)"
  fi
fi

upsert_env_file(){ local file="$1"; local k="$2"; local v="$3"; local tmp="${file}.tmp"; awk -v k="$k" -v v="$v" 'BEGIN{done=0}{ if(!done && $0 ~ "^" k "=") { print k"="v; done=1 } else { print $0 } } END{ if(!done) print k"="v }' "$file" > "$tmp"; mv "$tmp" "$file"; }
upsert_env(){ local k="$1"; local v="$2"; upsert_env_file "$ENV_FILE" "$k" "$v"; }
merge_csv_unique(){ local csv="$1"; local item="$2"; awk -v csv="$csv" -v item="$item" 'BEGIN{ n=split(csv,a,/[ ,]+/); for(i=1;i<=n;i++) if(length(a[i])) { if(!s[a[i]]) { s[a[i]]=1; o[++m]=a[i] } } if(length(item)&&!s[item]) o[++m]=item; for(i=1;i<=m;i++){ if(i>1) printf ","; printf "%s", o[i] } printf "\n" }'; }
upsert_if_empty(){ local k="$1"; local v="$2"; if ! grep -q "^${k}=" "$ENV_FILE" || grep -q "^${k}=\s*$" "$ENV_FILE"; then upsert_env "$k" "$v"; fi }

wait_for_supabase_ready(){
  local kong_container="$1"
  local attempts=30
  local url="http://${kong_container}:8000/rest/v1/?select=*"
  for attempt in $(seq 1 $attempts); do
    # Use lightweight curl container to avoid relying on host binaries
    status=$(docker run --rm --network supabase_network_supabase curlimages/curl:8.8.0 -s -o /dev/null -w '%{http_code}' "$url" 2>/dev/null || true)
    if [[ -n "$status" && "$status" != "000" ]]; then
      ok "Supabase API reachable (HTTP $status)"
      return 0
    fi
    sleep 2
  done
  err "Supabase API not reachable at $url after $attempts attempts"; exit 1
}

wait_for_supabase_table(){
  local kong_container="$1"
  local table="$2"
  local api_key="$3"
  local attempts=30
  local url="http://${kong_container}:8000/rest/v1/${table}?select=*"
  for attempt in $(seq 1 $attempts); do
    status=$(docker run --rm --network supabase_network_supabase \
      curlimages/curl:8.8.0 -s -o /dev/null -w '%{http_code}' -H "apikey: $api_key" "$url" 2>/dev/null || true)
    if [[ "$status" == "200" ]]; then
      ok "Supabase table ${table} reachable"
      return 0
    fi
    sleep 2
  done
  err "Supabase table ${table} not reachable at $url"; exit 1
}

# Populate essential defaults non-interactively (idempotent)
upsert_if_empty HOST "localhost"
upsert_if_empty ARCHON_SERVER_PORT "8181"
upsert_if_empty ARCHON_MCP_PORT "8051"
upsert_if_empty ARCHON_AGENTS_PORT "8052"
upsert_if_empty ARCHON_UI_PORT "3737"
upsert_if_empty AGENT_WORK_ORDERS_PORT "8053"
upsert_if_empty VITE_SHOW_DEVTOOLS "false"
# OpenObserve OTLP uses port 5080 with /api/{org} path, NOT 4317/4318
upsert_if_empty OTEL_EXPORTER_OTLP_ENDPOINT "http://localhost:5080/api/default"
upsert_if_empty OTEL_EXPORTER_OTLP_PROTOCOL "http/protobuf"
upsert_if_empty OTEL_EXPORTER_OTLP_ENDPOINT_CONTAINER "http://openobserve:5080/api/default"
upsert_if_empty OPENOBSERVE_USER "admin@archon.local"
upsert_if_empty OPENOBSERVE_PASSWORD "archon123"
upsert_if_empty OTEL_TRACES_EXPORTER "otlp"
upsert_if_empty OTEL_LOGS_EXPORTER "otlp"
upsert_if_empty OTEL_METRICS_EXPORTER "otlp"
upsert_if_empty OTEL_TRACES_SAMPLER "always_on"
upsert_if_empty OTEL_SERVICE_NAME_ARCHON_SERVER "archon-server"
upsert_if_empty OTEL_SERVICE_NAME_ARCHON_MCP "archon-mcp"
upsert_if_empty OTEL_SERVICE_NAME_ARCHON_AGENTS "archon-agents"

# Ensure OTLP auth header matches OpenObserve credentials (for local ingest/auth checks)
OPENOBSERVE_USER_VAL=$(grep -E '^OPENOBSERVE_USER=' "$ENV_FILE" | tail -n1 | cut -d= -f2- || true)
OPENOBSERVE_PASSWORD_VAL=$(grep -E '^OPENOBSERVE_PASSWORD=' "$ENV_FILE" | tail -n1 | cut -d= -f2- || true)
OTLP_HEADERS_VAL_RAW=$(grep -E '^OTEL_EXPORTER_OTLP_HEADERS=' "$ENV_FILE" | tail -n1 | cut -d= -f2- || true)
OTLP_HEADERS_VAL="${OTLP_HEADERS_VAL_RAW%\"}"
OTLP_HEADERS_VAL="${OTLP_HEADERS_VAL#\"}"
if [[ -n "$OPENOBSERVE_USER_VAL" && -n "$OPENOBSERVE_PASSWORD_VAL" ]]; then
  if command -v base64 >/dev/null 2>&1; then
    OO_BASIC=$(printf '%s' "${OPENOBSERVE_USER_VAL}:${OPENOBSERVE_PASSWORD_VAL}" | base64 | tr -d '\n')
  else
    OO_BASIC=$(python3 - <<PY
import base64
user = "${OPENOBSERVE_USER_VAL}"
password = "${OPENOBSERVE_PASSWORD_VAL}"
print(base64.b64encode(f"{user}:{password}".encode()).decode(), end="")
PY
)
  fi
  if [[ -n "${OO_BASIC:-}" ]]; then
    DESIRED_HEADERS="Authorization=Basic ${OO_BASIC}"
    DESIRED_HEADERS_QUOTED="\"${DESIRED_HEADERS}\""
    if [[ -z "$OTLP_HEADERS_VAL" ]]; then
      upsert_env OTEL_EXPORTER_OTLP_HEADERS "$DESIRED_HEADERS_QUOTED"
    elif [[ "$OTLP_HEADERS_VAL" == Authorization=Basic* && "$OTLP_HEADERS_VAL" != "$DESIRED_HEADERS" ]]; then
      upsert_env OTEL_EXPORTER_OTLP_HEADERS "$DESIRED_HEADERS_QUOTED"
    elif [[ "$OTLP_HEADERS_VAL" == Authorization=Basic* && "$OTLP_HEADERS_VAL_RAW" != "$DESIRED_HEADERS_QUOTED" ]]; then
      upsert_env OTEL_EXPORTER_OTLP_HEADERS "$DESIRED_HEADERS_QUOTED"
    fi
    ARCHON_SRC_ENV="${ARCHON_SRC_DIR:-$ROOT_DIR/archon-src}/.env"
    if [[ -f "$ARCHON_SRC_ENV" ]]; then
      upsert_env_file "$ARCHON_SRC_ENV" OTEL_EXPORTER_OTLP_HEADERS "$DESIRED_HEADERS_QUOTED"
    fi
  fi
fi

# Generate stable encryption key for credentials if not present
# This key persists across Supabase restarts (unlike SUPABASE_SERVICE_KEY which regenerates)
if ! grep -q "^CREDENTIAL_ENCRYPTION_KEY=" "$ENV_FILE" || grep -q "^CREDENTIAL_ENCRYPTION_KEY=\s*$" "$ENV_FILE"; then
  # Use Python to generate Fernet-compatible key (try local python first, then docker)
  CRED_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null || \
             docker run --rm python:3.12-slim pip install -q cryptography && python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null || \
             docker run --rm python:3.12-slim bash -c "pip install -q cryptography && python3 -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())'")
  if [[ -n "$CRED_KEY" ]]; then
    upsert_env CREDENTIAL_ENCRYPTION_KEY "$CRED_KEY"
    ok "Generated stable credential encryption key"
  else
    warn "Could not generate credential encryption key - credentials may not persist across restarts"
  fi
fi

[[ $enable_agents -eq 1 ]] && upsert_env AGENTS_ENABLED true || upsert_env AGENTS_ENABLED false

# Default images (idempotent). Compose fails fast if not present locally or pullable.
upsert_if_empty ARCHON_SERVER_IMAGE "archon-archon-server:latest"
upsert_if_empty ARCHON_MCP_IMAGE "archon-archon-mcp:latest"
upsert_if_empty ARCHON_FRONTEND_IMAGE "archon-archon-frontend:latest"
[[ $enable_agents -eq 1 ]] && upsert_if_empty ARCHON_AGENTS_IMAGE "archon-archon-agents:latest" || true

# Ensure Supabase via Supabase CLI (npx) and populate .env. Fail fast if unavailable.
ensure_supabase_env(){
  command -v npx >/dev/null 2>&1 || { err "npx not found. Install Node.js (>=18) to use supabase CLI"; exit 1; }
  mkdir -p "$SUPABASE_DIR"
  pushd "$SUPABASE_DIR" >/dev/null

  # Check for version drift (warn if CLI version changed)
  if type -t check_version_drift >/dev/null 2>&1; then
    check_version_drift || true  # Continue even if drift detected
  fi

  # Pre-start cleanup to prevent container name conflicts
  if type -t cleanup_stale_containers >/dev/null 2>&1; then
    cleanup_stale_containers
  fi

  # Supabase CLI keeps config under ./supabase/config.toml
  if [[ ! -f "supabase/config.toml" ]]; then
    npx -y supabase@${SUPABASE_VERSION:-2.70.5} init || { err "Failed to initialize Supabase CLI project"; exit 1; }
  fi

  # Attempt to start Supabase, with automatic recovery for storage migration issues
  local start_attempts=${SUPABASE_START_ATTEMPTS:-1}
  local debug_flag=""
  [[ ${SUPABASE_DEBUG:-0} -eq 1 ]] && debug_flag="--debug"
  for attempt in $(seq 1 $start_attempts); do
    if npx -y supabase@${SUPABASE_VERSION:-2.70.5} start $debug_flag; then
      break
    else
      if [[ $attempt -lt $start_attempts ]]; then
        warn "Supabase start failed (attempt $attempt/$start_attempts). Attempting recovery..."
        # Check if storage container failed
        if docker logs supabase_storage_supabase 2>&1 | grep -q "duplicate key value violates unique constraint"; then
          warn "Storage migration conflict detected - resetting migrations and cleaning old images..."
          if type -t recover_storage_migrations >/dev/null 2>&1; then
            recover_storage_migrations
          else
            # Inline recovery if function not available
            docker exec supabase_db_supabase bash -c \
              'PGPASSWORD=postgres psql -U supabase_admin -d postgres -c "TRUNCATE storage.migrations RESTART IDENTITY CASCADE;"' 2>/dev/null || true
          fi
          # Clean old storage-api images to ensure CLI pulls correct version
          if type -t cleanup_old_supabase_images >/dev/null 2>&1; then
            cleanup_old_supabase_images
          fi
        fi
        # Clean up and retry
        npx -y supabase@${SUPABASE_VERSION:-2.70.5} stop 2>/dev/null || true
        if type -t cleanup_stale_containers >/dev/null 2>&1; then
          cleanup_stale_containers
        fi
      else
        err "Failed to start local Supabase via CLI after $start_attempts attempts"
        exit 1
      fi
    fi
  done

  # Verify port bindings - fail fast if containers started without host bindings
  # This can happen when Docker restarts containers (via restart policy) without
  # going through the Supabase CLI, which manages port mappings
  if type -t verify_supabase_port_bindings >/dev/null 2>&1; then
    if ! verify_supabase_port_bindings; then
      if [[ $no_port_check -eq 1 ]]; then
        warn "Port bindings missing - continuing anyway (--no-port-check)"
      else
        warn "Port bindings missing - attempting recovery restart..."
        npx -y supabase@${SUPABASE_VERSION:-2.70.5} stop
        npx -y supabase@${SUPABASE_VERSION:-2.70.5} start

        # Second check - fail hard if still broken
        if ! verify_supabase_port_bindings; then
          err "FATAL: Supabase port bindings failed after recovery restart"
          err "External apps will NOT be able to connect to Supabase"
          err "Use --no-port-check to continue anyway for debugging"
          err "Try: npx supabase@${SUPABASE_VERSION:-2.70.5} stop && npx supabase@${SUPABASE_VERSION:-2.70.5} start"
          exit 1
        fi
      fi
    fi
  fi

  # Enforce shm_size on Postgres container (Supabase CLI ignores Docker daemon defaults)
  # Native Docker may require root; Docker Desktop can recreate as non-root
  if type -t enforce_postgres_shm_size >/dev/null 2>&1; then
    local desired_shm_bytes
    desired_shm_bytes="${POSTGRES_SHM_SIZE_BYTES:-4294967296}"
    if ! enforce_postgres_shm_size supabase_db_supabase "$desired_shm_bytes"; then
      if [[ $EUID -ne 0 ]]; then
        # Attempt non-interactive sudo (avoid hanging on password prompt)
        if command -v sudo >/dev/null 2>&1; then
          sudo -n bash -lc "source \"$ROOT_DIR/lib/supabase-utils.sh\" && enforce_postgres_shm_size supabase_db_supabase \"$desired_shm_bytes\"" || true
        fi
      fi
    fi

    # Fail fast if shm_size is still too small
    local current_shm
    current_shm=$(docker inspect -f '{{.HostConfig.ShmSize}}' supabase_db_supabase 2>/dev/null || echo "0")
    if [[ "$current_shm" -lt "$desired_shm_bytes" ]]; then
      err "Postgres shm_size is $(numfmt --to=iec "$current_shm" 2>/dev/null || echo "${current_shm} bytes") (required: $(numfmt --to=iec "$desired_shm_bytes" 2>/dev/null || echo "${desired_shm_bytes} bytes"))"
      docker_os=$(docker info -f '{{.OperatingSystem}}' 2>/dev/null || true)
      if [[ "$docker_os" == *"Docker Desktop"* ]]; then
        err "Docker Desktop detected: shm_size enforcement failed. Check bootstrap logs for container recreation errors."
      else
        err "Run bootstrap-archon.sh with sudo (so shm_size can be enforced)."
      fi
      exit 1
    fi
  fi

  # Query status in env format and parse required values
  STATUS_ENV=$(npx -y supabase@${SUPABASE_VERSION:-2.70.5} status -o env) || { err "Failed to get Supabase status"; exit 1; }
  SERVICE_ROLE_KEY=$(echo "$STATUS_ENV" | awk -F'=' '/^SERVICE_ROLE_KEY/{gsub(/"/,"",$2); print $2}')
  API_URL=$(echo "$STATUS_ENV" | awk -F'=' '/^API_URL/{gsub(/"/,"",$2); print $2}')
  popd >/dev/null
  if [[ -z "$SERVICE_ROLE_KEY" || -z "$API_URL" ]]; then
    err "Supabase status missing SERVICE_ROLE_KEY or API_URL; cannot continue"; exit 1
  fi
  upsert_env SUPABASE_URL "$API_URL"
  SUPABASE_KONG=$(docker ps --format '{{.Names}}' | grep -m1 'supabase_kong' || true)
  if [[ -n "$SUPABASE_KONG" ]]; then
    # Resolve container name to IP for upstream URL validation compatibility
    # (upstream rejects container hostnames but accepts RFC 1918 private IPs)
    KONG_IP=$(docker inspect "$SUPABASE_KONG" --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 2>/dev/null | head -1)
    if [[ -n "$KONG_IP" ]]; then
      upsert_env SUPABASE_URL_CONTAINER "http://${KONG_IP}:8000"
    else
      # Fallback to container name - will likely fail upstream URL validation
      warn "Could not resolve Kong container IP. Server may fail to start."
      upsert_env SUPABASE_URL_CONTAINER "http://$SUPABASE_KONG:8000"
    fi
    wait_for_supabase_ready "$SUPABASE_KONG"
  else
    upsert_env SUPABASE_URL_CONTAINER "http://host.docker.internal:54321"
  fi
  upsert_env SUPABASE_SERVICE_KEY "$SERVICE_ROLE_KEY"

  # Record successful version for future drift detection
  if type -t record_supabase_version >/dev/null 2>&1; then
    record_supabase_version
  fi

  ok "Supabase configured via supabase CLI"
}

ensure_supabase_env

# Host handling
IS_WSL=0
if [[ -f /proc/sys/kernel/osrelease ]] && grep -qi "microsoft" /proc/sys/kernel/osrelease 2>/dev/null; then
  IS_WSL=1
fi

CURRENT_HOST=$(grep -E '^HOST=' "$ENV_FILE" | sed 's/^HOST=//;s/\r$//' || true)
if [[ -n "$HOST_OVERRIDE" ]]; then
  upsert_env HOST "$HOST_OVERRIDE"
elif [[ $IS_WSL -eq 1 ]]; then
  if [[ -z "$CURRENT_HOST" || "$CURRENT_HOST" =~ ^172\. ]]; then
    upsert_env HOST "localhost"
  fi
fi

HOST_VAL=$(grep -E '^HOST=' "$ENV_FILE" | sed 's/^HOST=//;s/\r$//'); HOST_VAL=${HOST_VAL:-localhost}
existing=$(grep -E '^VITE_ALLOWED_HOSTS=' "$ENV_FILE" | sed 's/^VITE_ALLOWED_HOSTS=//;s/\r$//') || existing=""
upsert_env VITE_ALLOWED_HOSTS "$(merge_csv_unique "$existing" "$HOST_VAL")"
# Single-port toggle: only set if missing; otherwise preserve
if ! grep -q '^PROD=' "$ENV_FILE" || grep -q '^PROD=\s*$' "$ENV_FILE"; then
  if [[ $enable_single_port -eq 1 ]]; then upsert_env PROD true; else upsert_env PROD false; fi
fi

# Observability config
SKIP_COMPOSE_OBS=0
case "$observability" in
  compose)
    # OpenObserve uses 5080/api/default, not standard OTLP ports 4317/4318
    upsert_env OTEL_EXPORTER_OTLP_ENDPOINT_CONTAINER "http://openobserve:5080/api/default"
    if container_exists openobserve; then SKIP_COMPOSE_OBS=1; ok "Reusing existing openobserve"; fi
    ;;
  script)
    upsert_env OTEL_EXPORTER_OTLP_ENDPOINT_CONTAINER "http://host.docker.internal:4318"
    if [[ -x "$ROOT_DIR/setup-local-observability.sh" ]]; then "$ROOT_DIR/setup-local-observability.sh"; else warn "setup-local-observability.sh not found"; fi
    ;;
  none) warn "Observability disabled" ;;
  *) err "Invalid observability: $observability"; exit 1;;
esac

# Verify archon-src exists (bootstrap must be run first)
if [[ ! -f "$ARCHON_SRC_DIR/docker-compose.yml" ]]; then
  err "archon-src not found at $ARCHON_SRC_DIR"
  err "Run 'sudo ./bootstrap-archon.sh' first to clone the repository"
  exit 1
fi

if [[ -d "$ARCHON_SRC_DIR/.git" ]]; then
  CURRENT_BRANCH=$(git -C "$ARCHON_SRC_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
  if [[ "$CURRENT_BRANCH" != "$ARCHON_SRC_BRANCH" ]]; then
    warn "archon-src checked out to $CURRENT_BRANCH (expected $ARCHON_SRC_BRANCH). Using current branch."
  else
    ok "archon-src on $ARCHON_SRC_BRANCH"
  fi
else
  warn "archon-src does not appear to be a git repository; continuing"
fi

# Sync Supabase settings into archon-src/.env
SRC_ENV="$ARCHON_SRC_DIR/.env"
upsert_src_env(){ local k="$1"; local v="$2"; local tmp="$SRC_ENV.tmp"; awk -v k="$k" -v v="$v" 'BEGIN{done=0}{ if(!done && $0 ~ "^" k "=") { print k"="v; done=1 } else { print $0 } } END{ if(!done) print k"="v }' "$SRC_ENV" > "$tmp"; mv "$tmp" "$SRC_ENV"; }
CONTAINER_SUPABASE_URL=$(grep -E '^SUPABASE_URL_CONTAINER=' "$ENV_FILE" | sed 's/^SUPABASE_URL_CONTAINER=//' | tr -d '\r')
if [[ -n "$CONTAINER_SUPABASE_URL" ]]; then
  upsert_src_env SUPABASE_URL "$CONTAINER_SUPABASE_URL"
else
  upsert_src_env SUPABASE_URL "$(grep -E '^SUPABASE_URL=' "$ENV_FILE" | sed 's/^SUPABASE_URL=//' | tr -d '\r')"
fi
SUPABASE_SERVICE_KEY_VAL="$(grep -E '^SUPABASE_SERVICE_KEY=' "$ENV_FILE" | sed 's/^SUPABASE_SERVICE_KEY=//')"
upsert_src_env SUPABASE_SERVICE_KEY "$SUPABASE_SERVICE_KEY_VAL"

# Sync CREDENTIAL_ENCRYPTION_KEY to archon-src/.env for container use
CRED_KEY_VAL="$(grep -E '^CREDENTIAL_ENCRYPTION_KEY=' "$ENV_FILE" | sed 's/^CREDENTIAL_ENCRYPTION_KEY=//')"
if [[ -n "$CRED_KEY_VAL" ]]; then
  upsert_src_env CREDENTIAL_ENCRYPTION_KEY "$CRED_KEY_VAL"
fi

upsert_src_env HOST "$(grep -E '^HOST=' "$ENV_FILE" | sed 's/^HOST=//')"
upsert_src_env ARCHON_SERVER_PORT "$(grep -E '^ARCHON_SERVER_PORT=' "$ENV_FILE" | sed 's/^ARCHON_SERVER_PORT=//')"
upsert_src_env ARCHON_MCP_PORT "$(grep -E '^ARCHON_MCP_PORT=' "$ENV_FILE" | sed 's/^ARCHON_MCP_PORT=//')"
upsert_src_env ARCHON_AGENTS_PORT "$(grep -E '^ARCHON_AGENTS_PORT=' "$ENV_FILE" | sed 's/^ARCHON_AGENTS_PORT=//')"
upsert_src_env ARCHON_UI_PORT "$(grep -E '^ARCHON_UI_PORT=' "$ENV_FILE" | sed 's/^ARCHON_UI_PORT=//')"

# Run preflight checks if available
if type -t preflight_checks >/dev/null 2>&1; then
  preflight_checks || warn "Some preflight checks failed - continuing anyway"
fi

# Auto-backup before fresh install
if [[ $fresh_install -eq 1 ]]; then
  if type -t auto_backup >/dev/null 2>&1; then
    auto_backup "pre-fresh"
  fi
fi

# Run database migrations (idempotent, optional) before starting services
if [[ $run_migrations -eq 1 ]]; then
  echo "Running database migrations..."

  # Copy fresh migration files from archon-src
  if [[ -d "$ARCHON_SRC_DIR/migration" ]]; then
    echo "Copying migration files from archon-src..."
    # Copy root-level SQL files
    cp -f "$ARCHON_SRC_DIR/migration"/*.sql "$ROOT_DIR/migration/" 2>/dev/null || true
    # Copy all versioned subdirectories (0.1.0, 0.2.0, etc.)
    for subdir in "$ARCHON_SRC_DIR/migration"/*/; do
      if [[ -d "$subdir" ]]; then
        subdir_name=$(basename "$subdir")
        mkdir -p "$ROOT_DIR/migration/$subdir_name"
        cp -f "$subdir"*.sql "$ROOT_DIR/migration/$subdir_name/" 2>/dev/null || true
      fi
    done
    ok "Migration files copied from $ARCHON_SRC_DIR"
  else
    warn "archon-src migration dir not found at $ARCHON_SRC_DIR/migration, using existing migration files"
  fi

  DB_CONTAINER=$(docker ps --format '{{.Names}}' | grep -m1 'supabase_db' || true)
  DB_HOST=${DB_CONTAINER:-supabase_db_supabase}
  DB_PORT=5432; DB_USER=postgres; DB_PASSWORD=postgres; DB_NAME=postgres
  for i in {1..30}; do
    if docker run --rm --network supabase_network_supabase -e PGPASSWORD="$DB_PASSWORD" postgres:15-alpine pg_isready -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" >/dev/null 2>&1; then
      ok "Database reachable"
      break
    fi
    sleep 2
    [[ $i -eq 30 ]] && err "Database not reachable on $DB_HOST:$DB_PORT; failing fast" && exit 1
  done

  # Run migrations (run_migrations.py handles complete_setup.sql and numbered migrations)
  MIGRATION_ARGS=""
  [[ $fresh_install -eq 1 ]] && MIGRATION_ARGS="--fresh" && warn "FRESH INSTALL: Database will be wiped and reinstalled!"

  docker run --rm --network supabase_network_supabase \
    -e DB_HOST="$DB_HOST" -e DB_PORT="$DB_PORT" -e DB_USER="$DB_USER" -e DB_PASSWORD="$DB_PASSWORD" -e DB_NAME="$DB_NAME" \
    -e PIP_ROOT_USER_ACTION=ignore -e PIP_DISABLE_PIP_VERSION_CHECK=1 \
    -v "$ROOT_DIR":/work -w /work \
    python:3.12-slim bash -lc "pip install -q --upgrade pip && pip install -q psycopg2-binary && python migration/run_migrations.py $MIGRATION_ARGS" \
    && ok "Migrations applied"
  if [[ -n "$SUPABASE_KONG" ]]; then
    wait_for_supabase_table "$SUPABASE_KONG" "archon_settings" "$SUPABASE_SERVICE_KEY_VAL"
  fi
fi

# OpenObserve compose file location (lives in aeo-archon, not archon-src)
OPENOBSERVE_COMPOSE="$ROOT_DIR/docker-compose.openobserve.yml"

# Bring up upstream Archon stack with OpenObserve if enabled
# Unset SUPABASE_URL to ensure docker compose reads from archon-src/.env (not shell env)
# The archon-src/.env has the container-compatible URL (supabase_kong_supabase:8000)
COMPOSE_CMD="docker compose"
if [[ "$observability" != "none" && -f "$OPENOBSERVE_COMPOSE" ]]; then
  COMPOSE_CMD="docker compose -f docker-compose.yml -f $OPENOBSERVE_COMPOSE"
  ok "Using OpenObserve from $OPENOBSERVE_COMPOSE"
fi
( cd "$ARCHON_SRC_DIR" && unset SUPABASE_URL && $COMPOSE_CMD up --build -d ) || { err "Failed to build or start archon from source"; exit 1; }

if [[ $enable_agents -eq 1 ]]; then
  ( cd "$ARCHON_SRC_DIR" && unset SUPABASE_URL && $COMPOSE_CMD --profile agents up -d ) || warn "Agents profile failed to start"
fi

if [[ $enable_work_orders -eq 1 ]]; then
  ( cd "$ARCHON_SRC_DIR" && unset SUPABASE_URL && $COMPOSE_CMD --profile work-orders up -d ) || warn "Work orders profile failed to start"
fi

# OpenObserve + Supabase network connectivity now handled in docker-compose.openobserve.yml
# The compose file defines supabase_network_supabase as external and connects all archon services

# Verify
check(){ curl -fsS -o /dev/null -m 5 "$1" >/dev/null 2>&1; }
check_service(){
  local label="$1"; local url="$2"; local attempts=${3:-10}; local delay=${4:-3}; local success_codes="${5:-200}"
  for attempt in $(seq 1 "$attempts"); do
    status=$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 "$url" 2>/dev/null || echo "000")
    if [[ " $success_codes " == *" $status "* ]]; then
      ok "$label ready"
      return 0
    fi
    sleep "$delay"
  done
  warn "$label not ready"
  return 1
}
if [[ $skip_verify -eq 0 ]]; then
  UI_PORT=$(grep -E '^ARCHON_UI_PORT=' "$ENV_FILE" | sed 's/^ARCHON_UI_PORT=//;s/\r$//'); UI_PORT=${UI_PORT:-3737}
  API_PORT=$(grep -E '^ARCHON_SERVER_PORT=' "$ENV_FILE" | sed 's/^ARCHON_SERVER_PORT=//;s/\r$//'); API_PORT=${API_PORT:-8181}
  MCP_PORT=$(grep -E '^ARCHON_MCP_PORT=' "$ENV_FILE" | sed 's/^ARCHON_MCP_PORT=//;s/\r$//'); MCP_PORT=${MCP_PORT:-8051}
  AGENTS_PORT=$(grep -E '^ARCHON_AGENTS_PORT=' "$ENV_FILE" | sed 's/^ARCHON_AGENTS_PORT=//;s/\r$//'); AGENTS_PORT=${AGENTS_PORT:-8052}
  PROD=$(grep -E '^PROD=' "$ENV_FILE" | sed 's/^PROD=//;s/\r$//')
  CHECK_HOST="localhost"
  check_service "UI" "http://$CHECK_HOST:$UI_PORT"
  check_service "API" "http://$CHECK_HOST:$API_PORT/health"
  if [[ "$PROD" == "true" ]]; then
    check_service "API via UI" "http://$CHECK_HOST:$UI_PORT/api/health"
  fi
  check_service "MCP" "http://$CHECK_HOST:$MCP_PORT/health" 20 3 "200 404"
  if [[ $enable_agents -eq 1 ]]; then
    check_service "Agents" "http://$CHECK_HOST:$AGENTS_PORT/health" 20 3
  fi
  if [[ $enable_work_orders -eq 1 ]]; then
    WORK_ORDERS_PORT=$(grep -E '^AGENT_WORK_ORDERS_PORT=' "$ENV_FILE" | sed 's/^AGENT_WORK_ORDERS_PORT=//;s/\r$//'); WORK_ORDERS_PORT=${WORK_ORDERS_PORT:-8053}
    check_service "Work Orders" "http://$CHECK_HOST:$WORK_ORDERS_PORT/health" 20 3
  fi
  if [[ "$observability" != "none" ]]; then
    check_service "OpenObserve UI" "http://$CHECK_HOST:5080/" 24 5 "200 201 204 301 302 303 307 308"
  fi
fi

UI_PORT=${UI_PORT:-$(grep -E '^ARCHON_UI_PORT=' "$ENV_FILE" | sed 's/^ARCHON_UI_PORT=//;s/\r$//')}
UI_PORT=${UI_PORT:-3737}
API_PORT=${API_PORT:-$(grep -E '^ARCHON_SERVER_PORT=' "$ENV_FILE" | sed 's/^ARCHON_SERVER_PORT=//;s/\r$//')}
API_PORT=${API_PORT:-8181}
MCP_PORT=${MCP_PORT:-$(grep -E '^ARCHON_MCP_PORT=' "$ENV_FILE" | sed 's/^ARCHON_MCP_PORT=//;s/\r$//')}
MCP_PORT=${MCP_PORT:-8051}
AGENTS_PORT=${AGENTS_PORT:-$(grep -E '^ARCHON_AGENTS_PORT=' "$ENV_FILE" | sed 's/^ARCHON_AGENTS_PORT=//;s/\r$//')}
AGENTS_PORT=${AGENTS_PORT:-8052}
PROD=${PROD:-$(grep -E '^PROD=' "$ENV_FILE" | sed 's/^PROD=//;s/\r$//')}

ALT_HOST=""
if [[ -f /proc/sys/kernel/osrelease ]] && grep -qi "microsoft" /proc/sys/kernel/osrelease 2>/dev/null; then
  ALT_HOST="localhost"
fi

echo -e "${GREEN}Done. Access:${NC}"
echo "- UI:  http://$HOST_VAL:$UI_PORT"
if [[ -n "$ALT_HOST" && "$ALT_HOST" != "$HOST_VAL" ]]; then
  echo "  (WSL) http://$ALT_HOST:$UI_PORT"
fi

if [[ "${PROD:-true}" == "true" ]]; then
  echo "- API: http://$HOST_VAL:$UI_PORT/api (single-port)"
  if [[ -n "$ALT_HOST" && "$ALT_HOST" != "$HOST_VAL" ]]; then
    echo "  (WSL) http://$ALT_HOST:$UI_PORT/api (single-port)"
  fi
else
  echo "- API: http://$HOST_VAL:$API_PORT"
  if [[ -n "$ALT_HOST" && "$ALT_HOST" != "$HOST_VAL" ]]; then
    echo "  (WSL) http://$ALT_HOST:$API_PORT"
  fi
fi

echo "- MCP: http://$HOST_VAL:$MCP_PORT"
if [[ -n "$ALT_HOST" && "$ALT_HOST" != "$HOST_VAL" ]]; then
  echo "  (WSL) http://$ALT_HOST:$MCP_PORT"
fi

if [[ $enable_agents -eq 1 ]]; then
  echo "- Agents: http://$HOST_VAL:$AGENTS_PORT"
  if [[ -n "$ALT_HOST" && "$ALT_HOST" != "$HOST_VAL" ]]; then
    echo "  (WSL) http://$ALT_HOST:$AGENTS_PORT"
  fi
fi

if [[ $enable_work_orders -eq 1 ]]; then
  WORK_ORDERS_PORT=${WORK_ORDERS_PORT:-$(grep -E '^AGENT_WORK_ORDERS_PORT=' "$ENV_FILE" | sed 's/^AGENT_WORK_ORDERS_PORT=//;s/\r$//')}
  WORK_ORDERS_PORT=${WORK_ORDERS_PORT:-8053}
  echo "- Work Orders: http://$HOST_VAL:$WORK_ORDERS_PORT"
  if [[ -n "$ALT_HOST" && "$ALT_HOST" != "$HOST_VAL" ]]; then
    echo "  (WSL) http://$ALT_HOST:$WORK_ORDERS_PORT"
  fi
fi

if [[ "$observability" != "none" ]]; then
  echo "- Observability: http://$HOST_VAL:5080"
  if [[ -n "$ALT_HOST" && "$ALT_HOST" != "$HOST_VAL" ]]; then
    echo "  (WSL) http://$ALT_HOST:5080"
  fi
  OO_USER=$(grep -E '^OPENOBSERVE_USER=' "$ENV_FILE" | tail -n1 | cut -d= -f2- || true)
  OO_PASS=$(grep -E '^OPENOBSERVE_PASSWORD=' "$ENV_FILE" | tail -n1 | cut -d= -f2- || true)
  echo "  (OpenObserve login: ${OO_USER:-admin@archon.local} / ${OO_PASS:-archon123})"
fi

# Record versions for debugging
if type -t record_versions >/dev/null 2>&1; then
  record_versions
fi

# Run E2E validation tests
if [[ $skip_verify -eq 0 ]]; then
  if [[ -f "$ROOT_DIR/lib/e2e-tests.sh" ]]; then
    source "$ROOT_DIR/lib/e2e-tests.sh"
    echo ""
    run_e2e_tests || warn "Some E2E tests failed - review output above"
  fi
fi
