#!/usr/bin/env bash
# Bootstrap Archon from source: clone repo, prep Supabase env, and launch
# Usage:
#   ./bootstrap-from-source.sh [--repo <url>] [--branch <name>] [--dir <path>] [--no-start]
# Defaults:
#   repo: https://github.com/coleam00/archon.git
#   branch: main
#   dir: ./archon-src

set -Eeuo pipefail
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ARCHON_REPO_URL="https://github.com/coleam00/archon.git"
ARCHON_BRANCH="main"
ARCHON_SRC_DIR="$ROOT_DIR/archon-src"
DO_START=1

ok(){ echo -e "${GREEN}✓${NC} $1"; }
warn(){ echo -e "${YELLOW}!${NC} $1"; }
err(){ echo -e "${RED}✗${NC} $1"; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) ARCHON_REPO_URL="${2:-}"; shift 2;;
    --branch) ARCHON_BRANCH="${2:-}"; shift 2;;
    --dir) ARCHON_SRC_DIR="${2:-}"; shift 2;;
    --no-start) DO_START=0; shift;;
    -h|--help)
      cat <<EOF
Usage: $(basename "$0") [--repo <url>] [--branch <name>] [--dir <path>] [--no-start]
EOF
      exit 0;;
    *) err "Unknown option: $1"; exit 1;;
  esac
done

command -v git >/dev/null 2>&1 || { err "git not found"; exit 1; }

if [[ -d "$ARCHON_SRC_DIR/.git" ]]; then
  echo "Repo exists at $ARCHON_SRC_DIR; updating..."
  git -C "$ARCHON_SRC_DIR" fetch --all --prune
  git -C "$ARCHON_SRC_DIR" checkout "$ARCHON_BRANCH"
  git -C "$ARCHON_SRC_DIR" pull --ff-only origin "$ARCHON_BRANCH"
  ok "Repository updated"
else
  echo "Cloning $ARCHON_REPO_URL into $ARCHON_SRC_DIR..."
  git clone --depth 1 --branch "$ARCHON_BRANCH" "$ARCHON_REPO_URL" "$ARCHON_SRC_DIR"
  ok "Repository cloned"
fi

# Prepare .env in repo
REPO_ENV="$ARCHON_SRC_DIR/.env"
if [[ ! -f "$REPO_ENV" ]]; then
  if [[ -f "$ARCHON_SRC_DIR/.env.example" ]]; then cp "$ARCHON_SRC_DIR/.env.example" "$REPO_ENV"; ok ".env created from .env.example";
  elif [[ -f "$ARCHON_SRC_DIR/.env.sample" ]]; then cp "$ARCHON_SRC_DIR/.env.sample" "$REPO_ENV"; ok ".env created from .env.sample";
  else echo "# Generated by bootstrap" > "$REPO_ENV"; ok ".env initialized"; fi
fi

# Helper to upsert k=v into .env
upsert_env(){ local envf="$1"; local k="$2"; local v="$3"; local tmp="$envf.tmp"; awk -v k="$k" -v v="$v" 'BEGIN{done=0}{ if(!done && $0 ~ "^" k "=") { print k"="v; done=1 } else { print $0 } } END{ if(!done) print k"="v }' "$envf" > "$tmp"; mv "$tmp" "$envf"; }

# Try to populate Supabase settings from local Supabase CLI project
SUPA_ENV_CANDIDATES=("$ROOT_DIR/supabase/.env" "$ARCHON_SRC_DIR/supabase/.env")
SUPABASE_URL_DEFAULT="http://127.0.0.1:54321"
SUPABASE_URL_CONTAINER_DEFAULT="http://host.docker.internal:54321"
FOUND_SUPA=0
for f in "${SUPA_ENV_CANDIDATES[@]}"; do
  if [[ -f "$f" ]]; then
    set -a; # shellcheck disable=SC1090
    source "$f"; set +a
    if [[ -n "${SERVICE_ROLE_KEY:-}" ]]; then
      upsert_env "$REPO_ENV" SUPABASE_URL "$SUPABASE_URL_DEFAULT"
      upsert_env "$REPO_ENV" SUPABASE_URL_CONTAINER "$SUPABASE_URL_CONTAINER_DEFAULT"
      upsert_env "$REPO_ENV" SUPABASE_SERVICE_KEY "$SERVICE_ROLE_KEY"
      ok "Supabase settings populated from $(realpath "$f")"
      FOUND_SUPA=1
      break
    fi
  fi

done

if [[ $FOUND_SUPA -eq 0 ]]; then
  warn "Supabase CLI env not found; you can run: (cd $ARCHON_SRC_DIR && npx supabase@latest init && npx supabase start)"
fi

# Ensure launcher is executable
chmod +x "$ARCHON_SRC_DIR/archon-up.sh" 2>/dev/null || true

if [[ $DO_START -eq 1 ]]; then
  echo "Starting Archon from source..."
  ( cd "$ARCHON_SRC_DIR" && bash ./archon-up.sh )
else
  ok "Bootstrap complete. To start: (cd $ARCHON_SRC_DIR && bash ./archon-up.sh)"
fi
